### ISSUE TITLE
Change calendar language

### ISSUE THREAD

**Issue by 0phoff** [danielpinto8zz6/budgie-calendar-applet#10]
Is there an option to change the language of the calendar?
I installed it on Ubuntu-budgie using `apt install budgie-calendar-applet` and it works, but the calendar is in German. On my Manjaro system, everything is in English though...

Is there a config file somewhere, where I can select the language?

**Comment by danielpinto8zz6** [comment]
Strange thing, the calendar language follows the system language, are you sure you have your language set to english?

**Comment by 0phoff** [comment]
Hmm, managed to solve it by reconfiguring my locale...
Guess something was not setup right!
