### ISSUE TITLE
Why not on solus repo?

### ISSUE THREAD

**Issue by Juankz** [danielpinto8zz6/budgie-calendar-applet#11]
There are some applets made by the community featuring on Solus software center (like caffeine), it would be cool to have this applet there too

**Comment by danielpinto8zz6** [comment]
I've already asked @ikeydoherty  to add it, let's see

**Comment by ikeydoherty** [comment]
There is no patch or package request for this but I'll add now.

**Comment by ikeydoherty** [comment]
Thargo: https://dev.solus-project.com/R3877:648c6565def4d3df4000407b8a39a3b5da181bc0
