### ISSUE TITLE
settings not retained from session to session

### ISSUE THREAD

**Issue by moore-bryan** [danielpinto8zz6/budgie-calendar-applet#14]
On the latest Solus release, budgie-calendar-applet settings are not maintained from session to session; i.e., when I customize the display to show "%A, %d %B %Y @ %I:%M %P" it is displayed properly, but when I shutdown and power back up & log in the applet reverts back to the default settings.

I couldn't find any logs to share, but if you direct me to some that may exist, I'll send them.

**Comment by danielpinto8zz6** [comment]
Fixed
