### ISSUE TITLE
Vertical clock for vertical panels

### ISSUE THREAD

**Issue by fn-ix** [danielpinto8zz6/budgie-calendar-applet#15]
Hi!

I'd like to request a clock layout for vertical panels. As horizontal space is limited, the clock's font ends up being very small:

![clock-1](https://user-images.githubusercontent.com/16854594/40675766-ea2e7ae2-6378-11e8-80e0-40fc12431365.png)

I'd recommend a design similar to the Sony Xperia clock, where the hour and minute displays occupy separate lines (with different emphasis for contrast):

![serveimage](https://user-images.githubusercontent.com/16854594/40675906-5c1f0efa-6379-11e8-9a60-934e34256e59.jpg)

I tried to achieve a similar result with the custom date feature, however, the font isn't enlarged to make use of the available horizontal space:

![clock-2](https://user-images.githubusercontent.com/16854594/40675937-73a22e54-6379-11e8-9285-f9de505368de.png)

**Comment by danielpinto8zz6** [comment]
Hi mate,
I don't know if that can work, because we support multiple formats, on android you see only one format

**Comment by fn-ix** [comment]
Wouldn't it be possible to make the font sizes dynamically scale with the panel's width, independent of the format used?

Or at the very least, the "vertical clock" option could function so that, when used together with any of the other pre-determined formats (show seconds, 24hr clock) changes their format to show each element on a new line, with the font sizes adjusted to properly make use of the space available, plus some emphasis added to the different elements for contrast.

**Comment by danielpinto8zz6** [comment]
about the font size, yes it's possible
I'll test a vertical clock option then

**Comment by danielpinto8zz6** [comment]
Hi,
So after some thinking, I decided that there is no need to add font setting.
So here you go:
Try this custom format: `<span size='15000'>%H</span> %M`
This will print hours in 15px font size, you can change it as you want

**Comment by fn-ix** [comment]
Works great, thanks!
