### ISSUE TITLE
Bug: Date twice

### ISSUE THREAD

**Issue by MrReSc** [danielpinto8zz6/budgie-calendar-applet#16]
If you first select "Show date" and then "Custom date", the date is displayed twice. In the video you can see the bug.
![ezgif com-optimize](https://user-images.githubusercontent.com/24952268/41190929-9a2918a0-6be7-11e8-864f-75af4a99770a.gif)

**Comment by danielpinto8zz6** [comment]
fixed https://github.com/danielpinto8zz6/budgie-calendar-applet/commit/4f6e36a954ddadb74ad93b95cb60aa079cfa321d
