### ISSUE TITLE
Custom date format reset to default after reboot

### ISSUE THREAD

**Issue by dtrunk90** [danielpinto8zz6/budgie-calendar-applet#18]
I have to change the custom date format after each boot. It's always reset to default.

**Comment by danielpinto8zz6** [comment]
I guess your applet is not updated. What version you have?

**Comment by dtrunk90** [comment]
```
$ sudo apt-cache policy budgie-calendar-applet 
budgie-calendar-applet:
  Installiert:           4.1-0ubuntu1~bionic
  Installationskandidat: 4.1-0ubuntu1~bionic
  Versionstabelle:
 *** 4.1-0ubuntu1~bionic 500
        500 http://ppa.launchpad.net/ubuntubudgie/backports/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by danielpinto8zz6** [comment]
Try to install directlly from this Repo. It the errors persists Ill take a look

**Comment by dtrunk90** [comment]
I don't know if it's enough to run the commands from the README (budgie-calendar-applet is still installed). The info dialog from the applet shows version "4.0". I'm confused now.

**Comment by danielpinto8zz6** [comment]
Its a bug. Does it works?

**Comment by dtrunk90** [comment]
Unfortunately not

**Comment by danielpinto8zz6** [comment]
OK, I'll take a look

**Comment by danielpinto8zz6** [comment]
fixed https://github.com/danielpinto8zz6/budgie-calendar-applet/commit/4f6e36a954ddadb74ad93b95cb60aa079cfa321d
