### ISSUE TITLE
Popover content uses only 3/4 of width

### ISSUE THREAD

**Issue by dtrunk90** [danielpinto8zz6/budgie-calendar-applet#19]
Using Material Design (Adapta) Theme the popover uses only 3/4 of the available width:
![bildschirmfoto vom 2018-10-26 20-52-37](https://user-images.githubusercontent.com/636557/47586784-638c6300-d961-11e8-9c01-074d2303f546.png)

**Comment by danielpinto8zz6** [comment]
fixed https://github.com/danielpinto8zz6/budgie-calendar-applet/commit/4f6e36a954ddadb74ad93b95cb60aa079cfa321d

**Comment by danielpinto8zz6** [comment]
to avoid issues, make sure you uninstall last version before instaling the newer
