### ISSUE TITLE
custom clock-format don't change

### ISSUE THREAD

**Issue by AXeL-dev** [danielpinto8zz6/budgie-calendar-applet#20]
when i activate custom clock format & change the format from budgie panel settings, the format won't change (clock isn't updated).

![screenshot 2018-10-29 13-37-47](https://user-images.githubusercontent.com/30635693/47650332-da9b4480-db77-11e8-9d69-11707a9b1c1f.png)

But, when i do that from/using dconf-editor it works.

![screenshot 2018-10-29 13-38-34](https://user-images.githubusercontent.com/30635693/47650361-edae1480-db77-11e8-902b-dcd43fcc7921.png)

so maybe the custom-format setting is not saved well when using budgie panel to edit it.

Finally, thanks for the nice applet!

P.S.: this issue was on earlier versions too & persist in version 5.1 also.

**Comment by danielpinto8zz6** [comment]
Check it now :)

**Comment by AXeL-dev** [comment]
Great, it works!

Thanks x)
