### ISSUE TITLE
week numbers

### ISSUE THREAD

**Issue by zahaim** [danielpinto8zz6/budgie-calendar-applet#21]
Any idea how complicated it may be to add week numbers (of year)?

**Comment by danielpinto8zz6** [comment]
where?

**Comment by zahaim** [comment]
When I click on the tray to see the calendar I would like to see week numbers on the left, similar to 
![image](https://user-images.githubusercontent.com/12673315/48268296-dfdc7700-e434-11e8-9f65-c5ea96b3324c.png)

**Comment by danielpinto8zz6** [comment]
I can do that, this weekend I'll take a look

**Comment by zahaim** [comment]
that would be great, thx

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/budgie-calendar-applet/commit/0929851c6ea6246b4354b34a9649553ae1da3bf5 ;)

**Comment by zahaim** [comment]
Awesome, many thanks!
Just wondering how to update my Ubuntu Budgie applet now but I will figure it out :)

**Comment by danielpinto8zz6** [comment]
Just follow the instructions on readme
