### ISSUE TITLE
Is the popup space on the calendar applet normal or is it a bug?

### ISSUE THREAD

**Issue by ghost** [danielpinto8zz6/budgie-calendar-applet#22]
![capture de 2018-12-21 18 20 57](https://user-images.githubusercontent.com/44109252/50356366-f4db1880-0551-11e9-888d-6e6be057dd09.png)

(**Solus** Budgie)

**Comment by danielpinto8zz6** [comment]
that's a bug wich was fixed a long time ago, maybe you're using an outdated version

**Comment by ghost** [comment]
Indeed, I have the v4.1-2, don't know why. I will have a look to my repo.
Thanks you for quick answer.

**Comment by danielpinto8zz6** [comment]
np, last release is 5.2
https://github.com/danielpinto8zz6/budgie-calendar-applet/releases
