### ISSUE TITLE
Add at-a-glance functionality

### ISSUE THREAD

**Issue by rosesproctor** [danielpinto8zz6/budgie-calendar-applet#27]
So I am a brand new coder, but I want to know how I can edit the applet.vala on my computer so that I can attempt to create some added functionality, like integration with the Budgie Calendar and an extra panel in the popover that displays events from a selected day.

Then, ideally, I want to be able to select an event in the popover and trigger the Budgie Calendar to open and show that event.

If I get it working, I want to submit my changes to the applet, if it looks like a good idea to the contributors here

**Comment by danielpinto8zz6** [comment]
Hi, yes, you can create pull request
