### ISSUE TITLE
Calendar is wrongly positionned when applet is clicked

### ISSUE THREAD

**Issue by efournival** [danielpinto8zz6/budgie-calendar-applet#3]
Hi,

I have written a PKGBUILD (basically a script that generates a package) on the ArchLinux AUR:
https://aur.archlinux.org/packages/budgie-calendar-applet-git/

During the testing of your useful applet, I noticed a bug on my setup.

Here is what happens when I click on the clock:
![click](https://cloud.githubusercontent.com/assets/5874026/25566564/92dd968e-2ddb-11e7-8042-f240c6534261.png)

After 1 second or less, I finally get the right positionning:
![after1sec](https://cloud.githubusercontent.com/assets/5874026/25566567/a0c7e286-2ddb-11e7-82d9-73935bf4e7cb.png)

Obviously, my choice was to configure the panel on the bottom of my screen, which undoubtly causes the bug.

**Comment by danielpinto8zz6** [comment]
Hi, That's a bug from solus, the pophovers don't work so well with the panel on the bottom, not my fault :)

**Comment by danielpinto8zz6** [comment]
Obs: you won't have that problem on last budgie version, it's fixed on 10.3.1

**Comment by efournival** [comment]
All right, fine then and thanks for the applet. :)
