### ISSUE TITLE
[Request]Add Albanian(sq) translations.

### ISSUE THREAD

**Issue by algent-al** [danielpinto8zz6/budgie-calendar-applet#33]
Already made a language request to https://www.transifex.com/danielpinto8zz6/budgie-calendar-applet/ and willing to do the translations.

**Comment by danielpinto8zz6** [comment]
Accepted

**Comment by algent-al** [comment]
Thanks. Translations done.

**Comment by byquanton** [comment]
![image](https://user-images.githubusercontent.com/32410361/114707610-b7a28200-9d2a-11eb-92ee-a3357a2ff765.png)
For "Show the clock at the format you want" there is a Space at the End of the Translation

**Comment by algent-al** [comment]
Sorry for that. Fixed now.
