### ISSUE TITLE
Can't install on ubuntu budgie

### ISSUE THREAD

**Issue by Epizefiri** [danielpinto8zz6/budgie-calendar-applet#4]
Can you provide instructions?

**Comment by danielpinto8zz6** [comment]
just make sure to install the dependencies.
I'll add soon instructions, thanks

**Comment by fossfreedom** [comment]
@Epizefiri we probably will make this applet available as a package to be installed - thinking of producing an "applet store" like capability in budgie-welcome.  As Daniel mentioned  - compilation is straightforward - just need to install the equivalent debian packages as listed.

**Comment by fossfreedom** [comment]
@Epizefiri package now available for 17.04 and 16.04 - (17.04 via ppa:ubuntubudgie/backports) install the package budgie-calendar-applet

**Comment by Epizefiri** [comment]
danke!
