### ISSUE TITLE
Suggestion: make the time/date display format available to be changed

### ISSUE THREAD

**Issue by fossfreedom** [danielpinto8zz6/budgie-calendar-applet#5]
One of the oft asked things I've noticed is users wanting to display time and date in a format they specify rather than as dictated by GNOME.

Would you consider this in-scope of this plugin? - i.e. put the sprintf format string displaying date and time in a gsetting schema so that a user can override that.

**Comment by danielpinto8zz6** [comment]
Like Budgie clock applet does?

**Comment by fossfreedom** [comment]
possibly - I was more thinking about this bit of hard-coding - 

private static const string date_format = "%e %b %Y";

people of different parts of the world use the date in different formats - so can this be exposed in gsettings rather than hard-coding? Or at the minimum use the locale date format?

Other people also would like to see in the panel both the time and date e.g.

Thur, 13:34
05 May, 1:20PM

So - are these sort of things in the scope of this plugin?

**Comment by danielpinto8zz6** [comment]
I can use locale date format and people can change format on gnome tweak tool, 
what you think?

**Comment by danielpinto8zz6** [comment]
I think that's what you looking for: 
https://github.com/danielpinto8zz6/budgie-calendar-applet/commit/a789ce5c0f43f120c5d5342bec6ad27fea2e431b

I didn't implemented gsettings yet, just a test...

**Comment by fossfreedom** [comment]
yes - works nicely. cheers!

If the format of what is displayed on the panel (and possibly the date hover popover?) can then be exposed via gsettings that would be brilliant.

**Comment by danielpinto8zz6** [comment]
I am thinking create a right click option or in raven plugin settings put that options, to show formats, show date, show seconds, etc...
the format I'll maybe put on a select box all the formats and the user chose one, instead of input box that could create issues

**Comment by danielpinto8zz6** [comment]
https://github.com/danielpinto8zz6/budgie-calendar-applet/commit/5234de1cd51863750f72da62afd3135b41aa69cb working with gsettings :), the design is a mess, I'll have to think how I'll put that buttons and options, just test, and give some feedback

**Comment by fossfreedom** [comment]
just love it! I used this to fiddle with the codes https://apidock.com/ruby/DateTime/strftime

Maybe leave the "Time and Date button" below the calendar.
Keep the format options together with the entry field underneath a collapsible widget - so you click the triangle to open more options.

**Comment by danielpinto8zz6** [comment]
I also thinked to put on raven applet settings, don't know, will test and see how it goes...

**Comment by danielpinto8zz6** [comment]
what do you think is better to choose the date format, use that entrybox or use an combobox with some formats and the user choose one of them?

**Comment by fossfreedom** [comment]
If you make it an editable combobox you can have the best of both - choose from a predefined list - and let the user edit what they want to see.

**Comment by drohm** [comment]
I like @fossfreedom's idea, giving best of both worlds.  Really looking forward to this.

**Comment by danielpinto8zz6** [comment]
It will be done, I already has the code done.
Next release probably

**Comment by danielpinto8zz6** [comment]
It's done :
https://github.com/danielpinto8zz6/budgie-calendar-applet/commit/69ad3ae599904fd4e5640148f679f4bc39757543

Fell free to test and give feedback.

ATENTION: It only works with budgie from git, because I ported to new budgie popover, so, I'm only releasing when budgie releases..
