### ISSUE TITLE
Release 5.3

### ISSUE THREAD

**Issue by fossfreedom** [danielpinto8zz6/budgie-calendar-applet#58]
Any chance that you can tag a v5.3 release please?  It would be nice to get an official release out rather than a 5.2 + lots of patches release for various distros.

TIA.

**Comment by danielpinto8zz6** [comment]
Yes of course, I've just merged a PR with a fix, is there any patch you want to submit? If so please create PR

**Comment by fossfreedom** [comment]
Just to clarify - all patches we carry have been cherry-picked from here.

Looking forward to seeing the new official 5.3 release.

**Comment by danielpinto8zz6** [comment]
oh, tought you was talking about external patches.

version 5.3 released
