### ISSUE TITLE
Integration with the google calendar

### ISSUE THREAD

**Issue by NigelGreenway** [danielpinto8zz6/budgie-calendar-applet#6]
When I've used Debian, I seem to remember the calendar widget integrated with google calendar.

This would be a nice to have if possible to show upcoming events for the selected date?

**Comment by danielpinto8zz6** [comment]
Does it makes sense?
since you can have it on gnome calendar, how should be events shown?

**Comment by NigelGreenway** [comment]
Sorry, I meant Fedora and not Debian... 

If you look at the following image, it gives upcoming events as an overview. I tend to only open the calendar if I need to, but it would be a nice entry point to see an overview of upcoming events and saves opening Gnome calendar.

![image](https://user-images.githubusercontent.com/2984008/27607478-ee3632e8-5b7b-11e7-821f-efd785baea16.png)

**Comment by danielpinto8zz6** [comment]
but, this is notifications of events, or it shows events when you click on a day?

**Comment by NigelGreenway** [comment]
To be honest I can not remember the full feature entirely as I just liked the list of upcoming events and I'm just seeing if it is feasible to have:

 - a list of upcoming events in the calendar by default
 - a list of events displayed for the chosen day

**Comment by danielpinto8zz6** [comment]
I can do it, but it is just a calendar applet, I don't want to add such thing, I want to keep it more simple, for that you had gnome-calendar, that shows those notifications, I think that's not needed
In future, if I change my mind, I'll tell here.

**Comment by NigelGreenway** [comment]
@danielpinto8zz6 that is fair enough.

Thank you for discussing it, and thank you for this applet. :smiley:

**Comment by danielpinto8zz6** [comment]
no problem, thank you for your feedback :D
