### ISSUE TITLE
[Solus] ninja fails with 2 errors

### ISSUE THREAD

**Issue by MrGreenTea** [danielpinto8zz6/budgie-calendar-applet#7]
When I run ninja, I get the following errors:
`~/.budgie-calendar-applet/build   master  ninja`
```
[1/3] Compiling Vala source ../src/CalendarApplet.vala.
FAILED: src/calendarapplet@sha/CalendarApplet.c src/calendarapplet.h src/calendarapplet.vapi 
valac -C --pkg budgie-1.0 --pkg gtk+-3.0 -d src/calendarapplet@sha --library=calendarapplet -H src/calendarapplet.h --use-header --vapi ../calendarapplet.vapi --pkg=config --vapidir=/home/jonas/.budgie-calendar-applet/vapi ../src/CalendarApplet.vala
../src/CalendarApplet.vala:43.5-43.18: error: The type name `Budgie.Popover' could not be found
    Budgie.Popover ? popover = null;
    ^^^^^^^^^^^^^^
../src/CalendarApplet.vala:57.50-57.69: error: The type name `Budgie.PanelPosition' could not be found
    public override void panel_position_changed (Budgie.PanelPosition position) {
                                                 ^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

I installed (hopefully) all dependencies by just copying the eopkg install command from the README.
`sudo eopkg it budgie-desktop-devel libgnome-desktop-devel vala`

Any help would be appreciated.

**Comment by danielpinto8zz6** [comment]
well, you need upstream budgie from github, I'm not releasing until budgie releases, so just use the last release, it will work

**Comment by MrGreenTea** [comment]
I see, that makes sense. Thanks for the quick help. Maybe you could add this information to the README?

**Comment by danielpinto8zz6** [comment]
I don't know if makes sense, git master is the "under development" of budgie calendar applet, the "Completly working" versions are the releases
