### ISSUE TITLE
popup date does not update

### ISSUE THREAD

**Issue by fossfreedom** [danielpinto8zz6/budgie-calendar-applet#8]
![workspace 1_063](https://user-images.githubusercontent.com/996240/28588250-e15e5cd8-7171-11e7-94f8-87cc7ddb98df.jpg)

As you can see on clicking the date displays the popup - the calendar date is correct however the larger date has not been updated.

This a a virtualbox VM started after several days being off.  Time synced ok as you can see in the panel.

This is the git code with the budgie-popover changes - running budgie-desktop-git

**Comment by danielpinto8zz6** [comment]
Nice catch, will fix soon, thanks :D
