### ISSUE TITLE
Cannot convert from Gtk.Popover to Budgie.Popover

### ISSUE THREAD

**Issue by Amathadius** [danielpinto8zz6/budgie-calendar-applet#9]
When I try to install this applet in the Budgie developpement/git in Archlinux, I got this error message

CalendarApplet.vala:155.42-155.48: error: Argument 2: Cannot convert from `Gtk.Popover' to `Budgie.Popover'
        manager.register_popover(widget, popover);

**Comment by danielpinto8zz6** [comment]
You need to have last budgie from git installed

**Comment by Amathadius** [comment]
That's the point, I have the git version installed and I can't install this applet. In fact, I can't install any others applets in budgie-git (for example screenshot-applet). Maybe there''s a patch that "break" older applets.

**Comment by danielpinto8zz6** [comment]
The gtk.popover doens't exist anymore in budgie desktop, it's replaced by budgiepopover
